package com.huwl.oracle.myweibo.wrapper;

import com.huwl.oracle.myweibo.pojo.Like;
import java.util.List;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int deleteByPrimaryKey(Integer likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    Like selectByPrimaryKey(Integer likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    List<Like> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int updateByPrimaryKey(Like record);
}