package com.huwl.oracle.myweibo.wrapper;

import com.huwl.oracle.myweibo.pojo.Repationship;
import java.util.List;

public interface RepationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int deleteByPrimaryKey(Integer relatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int insert(Repationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    Repationship selectByPrimaryKey(Integer relatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    List<Repationship> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int updateByPrimaryKey(Repationship record);
}