package com.huwl.oracle.myweibo.wrapper;

import com.huwl.oracle.myweibo.pojo.Replay;
import java.util.List;

public interface ReplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLAY
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int deleteByPrimaryKey(Integer replayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLAY
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int insert(Replay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLAY
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    Replay selectByPrimaryKey(Integer replayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLAY
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    List<Replay> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLAY
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int updateByPrimaryKey(Replay record);
}