package com.huwl.oracle.myweibo.wrapper;

import com.huwl.oracle.myweibo.pojo.UserGroup;
import java.util.List;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_GROUP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_GROUP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_GROUP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    UserGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_GROUP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    List<UserGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_GROUP
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int updateByPrimaryKey(UserGroup record);
}