package com.huwl.oracle.myweibo.wrapper;

import com.huwl.oracle.myweibo.pojo.Weibo;
import java.util.List;

public interface WeiboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEI_BO
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int deleteByPrimaryKey(Integer weiboId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEI_BO
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int insert(Weibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEI_BO
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    Weibo selectByPrimaryKey(Integer weiboId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEI_BO
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    List<Weibo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEI_BO
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    int updateByPrimaryKey(Weibo record);
}