package com.huwl.oracle.myweibo.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.COMMENT_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.COMMENT_CONTENT
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.COMMENT_TIME
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENTS.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.COMMENT_ID
     *
     * @return the value of COMMENTS.COMMENT_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.COMMENT_ID
     *
     * @param commentId the value for COMMENTS.COMMENT_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.COMMENT_CONTENT
     *
     * @return the value of COMMENTS.COMMENT_CONTENT
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.COMMENT_CONTENT
     *
     * @param commentContent the value for COMMENTS.COMMENT_CONTENT
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.COMMENT_TIME
     *
     * @return the value of COMMENTS.COMMENT_TIME
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.COMMENT_TIME
     *
     * @param commentTime the value for COMMENTS.COMMENT_TIME
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENTS.USER_ID
     *
     * @return the value of COMMENTS.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENTS.USER_ID
     *
     * @param userId the value for COMMENTS.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}