package com.huwl.oracle.myweibo.pojo;

import java.io.Serializable;
import java.util.Date;

public class Like  implements Serializable {
    private static final long serialVersionUID = -7898194272883238670L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.LIKE_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.LIKE_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Date likeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Weibo weibo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.LIKE_ID
     *
     * @return the value of LIKES.LIKE_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.LIKE_ID
     *
     * @param likeId the value for LIKES.LIKE_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.LIKE_TIME
     *
     * @return the value of LIKES.LIKE_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Date getLikeTime() {
        return likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.LIKE_TIME
     *
     * @param likeTime the value for LIKES.LIKE_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setLikeTime(Date likeTime) {
        this.likeTime = likeTime;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Weibo getWeibo() {
        return weibo;
    }

    public void setWeibo(Weibo weibo) {
        this.weibo = weibo;
    }

    @Override
    public String toString() {
        return "Like{" +
                "likeId=" + likeId +
                ", user=" + user +
                ", likeTime=" + likeTime +
                ", weibo=" + weibo +
                '}';
    }
}