package com.huwl.oracle.myweibo.pojo;

import java.util.Date;

public class Like {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.LIKE_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.LIKE_TIME
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Date likeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.WEIBO_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer weiboId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.LIKE_ID
     *
     * @return the value of LIKES.LIKE_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.LIKE_ID
     *
     * @param likeId the value for LIKES.LIKE_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.USER_ID
     *
     * @return the value of LIKES.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.USER_ID
     *
     * @param userId the value for LIKES.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.LIKE_TIME
     *
     * @return the value of LIKES.LIKE_TIME
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Date getLikeTime() {
        return likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.LIKE_TIME
     *
     * @param likeTime the value for LIKES.LIKE_TIME
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setLikeTime(Date likeTime) {
        this.likeTime = likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.WEIBO_ID
     *
     * @return the value of LIKES.WEIBO_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.WEIBO_ID
     *
     * @param weiboId the value for LIKES.WEIBO_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }
}