package com.huwl.oracle.myweibo.pojo;

import java.io.Serializable;
import java.util.Date;

public class Relationship  implements Serializable {
    private static final long serialVersionUID = -7898194272883238670L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RELATIONSHIP.RELAT_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer relatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RELATIONSHIP.STAR_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer starId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RELATIONSHIP.CARE_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Date careTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RELATIONSHIP.GROUP_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RELATIONSHIP.RELAT_ID
     *
     * @return the value of RELATIONSHIP.RELAT_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getRelatId() {
        return relatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RELATIONSHIP.RELAT_ID
     *
     * @param relatId the value for RELATIONSHIP.RELAT_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setRelatId(Integer relatId) {
        this.relatId = relatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RELATIONSHIP.STAR_ID
     *
     * @return the value of RELATIONSHIP.STAR_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getStarId() {
        return starId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RELATIONSHIP.STAR_ID
     *
     * @param starId the value for RELATIONSHIP.STAR_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setStarId(Integer starId) {
        this.starId = starId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RELATIONSHIP.CARE_TIME
     *
     * @return the value of RELATIONSHIP.CARE_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Date getCareTime() {
        return careTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RELATIONSHIP.CARE_TIME
     *
     * @param careTime the value for RELATIONSHIP.CARE_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setCareTime(Date careTime) {
        this.careTime = careTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RELATIONSHIP.GROUP_ID
     *
     * @return the value of RELATIONSHIP.GROUP_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RELATIONSHIP.GROUP_ID
     *
     * @param groupId the value for RELATIONSHIP.GROUP_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}