package com.huwl.oracle.myweibo.pojo;

import java.util.Date;

public class Replay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLAY.REPLAY_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer replayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLAY.REPLAY_CONTENT
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private String replayContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLAY.REPLAY_TIMIE
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Date replayTimie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLAY.TO_USER
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer toUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLAY.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLAY.REPLAY_ID
     *
     * @return the value of REPLAY.REPLAY_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getReplayId() {
        return replayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLAY.REPLAY_ID
     *
     * @param replayId the value for REPLAY.REPLAY_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setReplayId(Integer replayId) {
        this.replayId = replayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLAY.REPLAY_CONTENT
     *
     * @return the value of REPLAY.REPLAY_CONTENT
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public String getReplayContent() {
        return replayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLAY.REPLAY_CONTENT
     *
     * @param replayContent the value for REPLAY.REPLAY_CONTENT
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setReplayContent(String replayContent) {
        this.replayContent = replayContent == null ? null : replayContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLAY.REPLAY_TIMIE
     *
     * @return the value of REPLAY.REPLAY_TIMIE
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Date getReplayTimie() {
        return replayTimie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLAY.REPLAY_TIMIE
     *
     * @param replayTimie the value for REPLAY.REPLAY_TIMIE
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setReplayTimie(Date replayTimie) {
        this.replayTimie = replayTimie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLAY.TO_USER
     *
     * @return the value of REPLAY.TO_USER
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLAY.TO_USER
     *
     * @param toUser the value for REPLAY.TO_USER
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setToUser(Integer toUser) {
        this.toUser = toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLAY.USER_ID
     *
     * @return the value of REPLAY.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLAY.USER_ID
     *
     * @param userId the value for REPLAY.USER_ID
     *
     * @mbggenerated Mon Jul 17 19:04:18 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}