package com.huwl.oracle.myweibo.pojo;

import java.io.Serializable;
import java.util.Date;

public class UserGroup  implements Serializable {
    private static final long serialVersionUID = -7898194272883238670L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GROUP.GROUP_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GROUP.GROUP_NAME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GROUP.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GROUP.SET_UP_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Date setUpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GROUP.GROUP_ID
     *
     * @return the value of USER_GROUP.GROUP_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GROUP.GROUP_ID
     *
     * @param groupId the value for USER_GROUP.GROUP_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GROUP.GROUP_NAME
     *
     * @return the value of USER_GROUP.GROUP_NAME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GROUP.GROUP_NAME
     *
     * @param groupName the value for USER_GROUP.GROUP_NAME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GROUP.USER_ID
     *
     * @return the value of USER_GROUP.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GROUP.USER_ID
     *
     * @param userId the value for USER_GROUP.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GROUP.SET_UP_TIME
     *
     * @return the value of USER_GROUP.SET_UP_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Date getSetUpTime() {
        return setUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GROUP.SET_UP_TIME
     *
     * @param setUpTime the value for USER_GROUP.SET_UP_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public void setSetUpTime(Date setUpTime) {
        this.setUpTime = setUpTime;
    }
}