package com.huwl.oracle.myweibo.pojo;

import java.io.Serializable;
import java.util.Date;

public class Weibo  implements Serializable {
    private static final long serialVersionUID = -7898194272883238670L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.WEIBO_CONTENT
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private String weiboContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.PUBLISH_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.READ_TIMES
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer readTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.IS_REPOST
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Boolean isRepost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.REPOST_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer repostId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.WEIBO_ID
     *
     * @return the value of WEI_BO.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.WEIBO_ID
     *
     * @param weiboId the value for WEI_BO.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.USER_ID
     *
     * @return the value of WEI_BO.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.USER_ID
     *
     * @param userId the value for WEI_BO.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.WEIBO_CONTENT
     *
     * @return the value of WEI_BO.WEIBO_CONTENT
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public String getWeiboContent() {
        return weiboContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.WEIBO_CONTENT
     *
     * @param weiboContent the value for WEI_BO.WEIBO_CONTENT
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setWeiboContent(String weiboContent) {
        this.weiboContent = weiboContent == null ? null : weiboContent.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.PUBLISH_TIME
     *
     * @return the value of WEI_BO.PUBLISH_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.PUBLISH_TIME
     *
     * @param publishTime the value for WEI_BO.PUBLISH_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.READ_TIMES
     *
     * @return the value of WEI_BO.READ_TIMES
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getReadTimes() {
        return readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.READ_TIMES
     *
     * @param readTimes the value for WEI_BO.READ_TIMES
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setReadTimes(Integer readTimes) {
        this.readTimes = readTimes;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.IS_REPOST
     *
     * @return the value of WEI_BO.IS_REPOST
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Boolean getIsRepost() {
        return isRepost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.IS_REPOST
     *
     * @param isRepost the value for WEI_BO.IS_REPOST
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setIsRepost(Boolean isRepost) {
        this.isRepost = isRepost;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.REPOST_ID
     *
     * @return the value of WEI_BO.REPOST_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getRepostId() {
        return repostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.REPOST_ID
     *
     * @param repostId the value for WEI_BO.REPOST_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setRepostId(Integer repostId) {
        this.repostId = repostId;
        return this;
    }
}