package com.huwl.oracle.myweibo.pojo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Weibo  implements Serializable {
    private static final long serialVersionUID = -7898194272883238670L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.USER_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.WEIBO_CONTENT
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private String weiboContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.PUBLISH_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.READ_TIMES
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Integer readTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.IS_REPOST
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Boolean isRepost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEI_BO.REPOST_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    private Weibo repost;

    private String pics;
    private List<Like> likes;
    private List<Comment> comments;

    public List<Comment> getComments() {
        return comments;
    }
    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }
    public List<Like> getLikes() {
        return likes;
    }

    public void setLikes(List<Like> likes) {
        this.likes = likes;
    }

    public String getPics() {
        return pics;
    }

    public Weibo setPics(String pics) {
        this.pics = pics;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.WEIBO_ID
     *
     * @return the value of WEI_BO.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.WEIBO_ID
     *
     * @param weiboId the value for WEI_BO.WEIBO_ID
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
        return this;
    }

    public User getUser() {
        return user;
    }

    public Weibo setUser(User user) {
        this.user = user;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.WEIBO_CONTENT
     *
     * @return the value of WEI_BO.WEIBO_CONTENT
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public String getWeiboContent() {
        return weiboContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.WEIBO_CONTENT
     *
     * @param weiboContent the value for WEI_BO.WEIBO_CONTENT
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setWeiboContent(String weiboContent) {
        this.weiboContent = weiboContent == null ? null : weiboContent.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.PUBLISH_TIME
     *
     * @return the value of WEI_BO.PUBLISH_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.PUBLISH_TIME
     *
     * @param publishTime the value for WEI_BO.PUBLISH_TIME
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.READ_TIMES
     *
     * @return the value of WEI_BO.READ_TIMES
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Integer getReadTimes() {
        return readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.READ_TIMES
     *
     * @param readTimes the value for WEI_BO.READ_TIMES
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setReadTimes(Integer readTimes) {
        this.readTimes = readTimes;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEI_BO.IS_REPOST
     *
     * @return the value of WEI_BO.IS_REPOST
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Boolean getIsRepost() {
        return isRepost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEI_BO.IS_REPOST
     *
     * @param isRepost the value for WEI_BO.IS_REPOST
     *
     * @mbggenerated Tue Jul 18 08:02:56 CST 2017
     */
    public Weibo setIsRepost(Boolean isRepost) {
        this.isRepost = isRepost;
        return this;
    }

    public Weibo getRepost() {
        return repost;
    }

    public void setRepost(Weibo repost) {
        this.repost = repost;
    }

    @Override
    public String toString() {
        return "Weibo{" +
                "weiboId=" + weiboId +
                ", user=" + user +
                ", weiboContent='" + weiboContent + '\'' +
                ", publishTime=" + publishTime +
                ", readTimes=" + readTimes +
                ", isRepost=" + isRepost +
                ", repost=" + repost +
                ", pics='" + pics + '\'' +
                ", likes=" + likes +
                '}';
    }
}